### ISSUE TITLE
fix ppl exploit for Windows server 2012

### ISSUE THREAD

**Issue by VioletteCrew** [helpsystems/nanodump#22]
I tried nanodump_ppl bof, on a Windows server 2012,(lsa has ppl protection) and is fully updated. it doesn't work, any way to fix this?

**Comment by S4ntiagoP** [comment]
Hello mate,
You are right, it didn't work because there was a check that made sure that the windows version was greater or equal to 8.1, but apparently Windows Server 2012 has PPL support so I lowered the min version to 6.3
Let me know if you still have issues, I'm closing this for now.
Thank you for reporting!
